/**
 * Generate a string represents the environment variable name for the property of given resource object.
 * The result remains consistent between compile time and runtime.
 */
export function createEnvNameForProperty(
  resourceType: string,
  resourceId: string,
  propertyName: string
) {
  const envName = `${resourceType}_${resourceId}_${propertyName}`
    .toUpperCase()
    .replace(/[^a-zA-Z0-9_]/g, "_");
  return envName;
}

/**
 * Fetch the value that generated by infrastructure codes at compile time  of an environment variable.
 */
export function getEnvValForProperty(
  resourceType: string,
  resourceId: string,
  propertyName: string
): string {
  const envName = createEnvNameForProperty(resourceType, resourceId, propertyName);
  const value = process.env[envName];
  if (!value) {
    throw new Error(
      `The environment variable '${envName}', representing the value for '${propertyName}' associated with the '<${resourceType}>${resourceId}', cannot be located within the environment variables.`
    );
  }
  return value;
}
