ARG BASE_IMAGE

FROM --platform=$TARGETPLATFORM $BASE_IMAGE

ARG TARGETPLATFORM
ARG PYTHON_VERSION

# Install Python and pip packages
RUN apt-get update && \
    apt-get install -y python${PYTHON_VERSION} python3-pip python${PYTHON_VERSION}-venv python${PYTHON_VERSION}-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
